### ISSUE TITLE
Elm: Update elm-language-server integration

### ISSUE THREAD

**Issue by andys8** [dense-analysis/ale#2592]
@antew made great progress helping out to integrate the `@elm-tooling/elm-language-server` (see https://github.com/antew/vim-elm-language-server/commits/master)

## Tasks

- [x] Update the integration code (`elmTestPath` is new, executable path option name changed)
- [x] Make sure tests are working
- [x] Check if docs need to be updated (and link to how to install `elm-language-server`)
- [x] Update `elm-language-server` docs to link to `w0rp/ale` again: https://github.com/elm-tooling/elm-language-server#ale

**Comment by andys8** [comment]
I wouldn't remove redundant fixers/linters `elm make` and `elm-format` to let people decide what they want to use.

**Comment by andys8** [comment]
#2612 is merged into `master`
